// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.Infrastructure;

#nullable disable

namespace UserService.Infrastructure.Migrations
{
    [DbContext(typeof(UserServiceContext))]
    [Migration("20260619230215_AddEmailVerificationToken")]
    partial class AddEmailVerificationToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserService.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("email_verified");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UserService.Domain.Users.User", b =>
                {
                    b.OwnsOne("UserService.Domain.Users.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("UserService.Domain.Users.EmailVerificationToken", "VerificationToken", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("verification_token_created_at");

                            b1.Property<DateTime>("ExpiresAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("verification_token_expires_at");

                            b1.Property<string>("TokenHash")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("verification_token_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("UserService.Domain.Users.Passport", "Passport", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("BirthDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("birth_date");

                            b1.Property<string>("Name")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("first_name");

                            b1.Property<DateTime>("PassportIssueDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("passport_issue_date");

                            b1.Property<string>("Patronymic")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("patronymic");

                            b1.Property<string>("Surname")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("last_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsOne("UserService.Domain.Users.IdentityNumber", "IdentityNumber", b2 =>
                                {
                                    b2.Property<Guid>("PassportUserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .HasColumnType("nvarchar(450)")
                                        .HasColumnName("identity_number");

                                    b2.HasKey("PassportUserId");

                                    b2.HasIndex("Value")
                                        .IsUnique()
                                        .HasFilter("[identity_number] IS NOT NULL");

                                    b2.ToTable("users");

                                    b2.WithOwner()
                                        .HasForeignKey("PassportUserId");
                                });

                            b1.OwnsOne("UserService.Domain.Users.PassportNumber", "PassportNumber", b2 =>
                                {
                                    b2.Property<Guid>("PassportUserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .HasColumnType("nvarchar(450)")
                                        .HasColumnName("passport_number");

                                    b2.HasKey("PassportUserId");

                                    b2.HasIndex("Value")
                                        .IsUnique()
                                        .HasFilter("[passport_number] IS NOT NULL");

                                    b2.ToTable("users");

                                    b2.WithOwner()
                                        .HasForeignKey("PassportUserId");
                                });

                            b1.Navigation("IdentityNumber")
                                .IsRequired();

                            b1.Navigation("PassportNumber")
                                .IsRequired();
                        });

                    b.OwnsOne("UserService.Domain.Users.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("UserService.Domain.Users.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("phone_number");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Passport");

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();

                    b.Navigation("VerificationToken");
                });
#pragma warning restore 612, 618
        }
    }
}
