// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalService.Infrastructure;

#nullable disable

namespace RentalService.Infrastructure.Migrations
{
    [DbContext(typeof(RentalServiceContext))]
    [Migration("20260427080924_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentalService.Domain.Rentals.Rental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Rentals", (string)null);
                });

            modelBuilder.Entity("RentalService.Domain.Rentals.Rental", b =>
                {
                    b.OwnsOne("RentalService.Domain.Rentals.CarRenterSnapshot", "CarRenterSnapshot", b1 =>
                        {
                            b1.Property<Guid>("RentalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Renter_Name");

                            b1.Property<string>("Patronymic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Renter_Patronymic");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Renter_PhoneNumber");

                            b1.Property<string>("SurName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Renter_SurName");

                            b1.HasKey("RentalId");

                            b1.ToTable("Rentals");

                            b1.WithOwner()
                                .HasForeignKey("RentalId");
                        });

                    b.OwnsOne("RentalService.Domain.Rentals.RentCarSnapshot", "RentCarSnapshot", b1 =>
                        {
                            b1.Property<Guid>("RentalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AvailabilityStatus")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Car_AvailabilityStatus");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Car_Brand");

                            b1.Property<string>("CarClass")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Car_CarClass");

                            b1.Property<string>("Generation")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Car_Generation");

                            b1.Property<bool>("IsFacelift")
                                .HasColumnType("bit")
                                .HasColumnName("Car_IsFacelift");

                            b1.Property<string>("LicensePlate")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Car_LicensePlate");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Car_Model");

                            b1.Property<decimal>("PricePerHour")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Car_PricePerHour");

                            b1.Property<string>("Variant")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Car_Variant");

                            b1.HasKey("RentalId");

                            b1.ToTable("Rentals");

                            b1.WithOwner()
                                .HasForeignKey("RentalId");
                        });

                    b.Navigation("CarRenterSnapshot")
                        .IsRequired();

                    b.Navigation("RentCarSnapshot")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
