// <auto-generated />
using System;
using CarService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarService.Infrastructure.Migrations
{
    [DbContext(typeof(CarServiceDbContext))]
    [Migration("20260607112142_AddedCurrentRenterId")]
    partial class AddedCurrentRenterId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarService.Domain.Cars.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CurrentRenterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("current_renter_id");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("cars", (string)null);
                });

            modelBuilder.Entity("CarService.Domain.Cars.Car", b =>
                {
                    b.OwnsOne("CarService.Domain.Cars.Enums.Color", "Color", b1 =>
                        {
                            b1.Property<Guid>("CarId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("color");

                            b1.HasKey("CarId");

                            b1.ToTable("cars");

                            b1.WithOwner()
                                .HasForeignKey("CarId");
                        });

                    b.OwnsOne("CarService.Domain.Cars.ValueObjects.CarModelInfo", "ModelInfo", b1 =>
                        {
                            b1.Property<Guid>("CarId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("brand");

                            b1.Property<string>("Generation")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("generation");

                            b1.Property<bool>("IsFacelift")
                                .HasColumnType("bit")
                                .HasColumnName("is_facelift");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("model");

                            b1.Property<string>("Variant")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("variant");

                            b1.HasKey("CarId");

                            b1.ToTable("cars");

                            b1.WithOwner()
                                .HasForeignKey("CarId");
                        });

                    b.OwnsOne("CarService.Domain.Cars.ValueObjects.CarTechInfo", "TechInfo", b1 =>
                        {
                            b1.Property<Guid>("CarId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BodyStyle")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("body_style");

                            b1.Property<string>("DriveType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("drive_type");

                            b1.Property<double>("Mileage")
                                .HasColumnType("float")
                                .HasColumnName("mileage");

                            b1.Property<string>("TransmissionType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("transmission");

                            b1.HasKey("CarId");

                            b1.ToTable("cars");

                            b1.WithOwner()
                                .HasForeignKey("CarId");

                            b1.OwnsOne("CarService.Domain.Cars.ValueObjects.BatteryLevel", "BatteryLevel", b2 =>
                                {
                                    b2.Property<Guid>("CarTechInfoCarId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("CapacityKWh")
                                        .HasColumnType("float")
                                        .HasColumnName("battery_capacity_kwh");

                                    b2.Property<double>("CurrentKWh")
                                        .HasColumnType("float")
                                        .HasColumnName("battery_current_kwh");

                                    b2.HasKey("CarTechInfoCarId");

                                    b2.ToTable("cars");

                                    b2.WithOwner()
                                        .HasForeignKey("CarTechInfoCarId");
                                });

                            b1.OwnsOne("CarService.Domain.Cars.ValueObjects.EngineDetails", "EngineDetails", b2 =>
                                {
                                    b2.Property<Guid>("CarTechInfoCarId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("EngineType")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("engine_type");

                                    b2.Property<double>("HorsePower")
                                        .HasColumnType("float")
                                        .HasColumnName("engine_horse_power");

                                    b2.Property<double?>("PowerReverse")
                                        .HasColumnType("float")
                                        .HasColumnName("engine_power_reverse");

                                    b2.Property<double?>("Volume")
                                        .HasColumnType("float")
                                        .HasColumnName("engine_volume");

                                    b2.HasKey("CarTechInfoCarId");

                                    b2.ToTable("cars");

                                    b2.WithOwner()
                                        .HasForeignKey("CarTechInfoCarId");
                                });

                            b1.OwnsOne("CarService.Domain.Cars.ValueObjects.FuelTank", "FuelTank", b2 =>
                                {
                                    b2.Property<Guid>("CarTechInfoCarId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("CapacityLiters")
                                        .HasColumnType("float")
                                        .HasColumnName("fuel_capacity_liters");

                                    b2.Property<double>("CurrentLiters")
                                        .HasColumnType("float")
                                        .HasColumnName("fuel_current_liters");

                                    b2.HasKey("CarTechInfoCarId");

                                    b2.ToTable("cars");

                                    b2.WithOwner()
                                        .HasForeignKey("CarTechInfoCarId");
                                });

                            b1.Navigation("BatteryLevel");

                            b1.Navigation("EngineDetails")
                                .IsRequired();

                            b1.Navigation("FuelTank");
                        });

                    b.OwnsOne("CarService.Domain.Cars.ValueObjects.LicensePlate", "LicensePlate", b1 =>
                        {
                            b1.Property<Guid>("CarId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("license_plate");

                            b1.HasKey("CarId");

                            b1.ToTable("cars");

                            b1.WithOwner()
                                .HasForeignKey("CarId");
                        });

                    b.OwnsOne("CarService.Domain.Cars.ValueObjects.PricePerHour", "PricePerHour", b1 =>
                        {
                            b1.Property<Guid>("CarId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Price")
                                .HasColumnType("float")
                                .HasColumnName("price_per_hour");

                            b1.HasKey("CarId");

                            b1.ToTable("cars");

                            b1.WithOwner()
                                .HasForeignKey("CarId");
                        });

                    b.OwnsOne("CarService.Domain.Cars.ValueObjects.VinCode", "VinCode", b1 =>
                        {
                            b1.Property<Guid>("CarId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("vin_code");

                            b1.HasKey("CarId");

                            b1.ToTable("cars");

                            b1.WithOwner()
                                .HasForeignKey("CarId");
                        });

                    b.Navigation("Color")
                        .IsRequired();

                    b.Navigation("LicensePlate")
                        .IsRequired();

                    b.Navigation("ModelInfo")
                        .IsRequired();

                    b.Navigation("PricePerHour")
                        .IsRequired();

                    b.Navigation("TechInfo")
                        .IsRequired();

                    b.Navigation("VinCode")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
