<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>ContractService</RootNamespace>
      <UserSecretsId>e0b12f3a-aba8-4696-b42f-d46e87658ed0</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="16.1.1" />
        <PackageReference Include="itext" Version="8.0.5" />
        <PackageReference Include="itext.bouncy-castle-adapter" Version="8.0.5" />
        <PackageReference Include="MediatR" Version="14.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
        <PackageReference Include="Microsoft.Playwright" Version="1.60.0" />
        <PackageReference Include="PuppeteerSharp" Version="25.0.4" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ContractService.Infrastructure\ContractService.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="MappingRequests\" />
    </ItemGroup>

</Project>
